### ISSUE TITLE
Blocks overlay when the "contextual link" is active

### ISSUE THREAD

**Issue by vtad** [backdrop-contrib/fanciblock#1]
A "normal" block overlays partially the fanciblock when logged in as a admin and the contextual links are active:
![09-03-_2015_09-56-56](https://cloud.githubusercontent.com/assets/10612817/6552146/c312e1ea-c642-11e4-9409-2e3cc7295ff4.png)

For the correct display (terminef1 is the fanciblock)  wee http://opi.vtadtest.de/

**Comment by docwilmot** [comment]
Could you do me a favor and flush your CSS and Javascript cache please? The height is not being calculated properly I suspect.
Not that this would be the solution, but just want to check if that helps.

**Comment by vtad** [comment]
I had allready flushed all the caches inclusive css Javascript and 
Browser caches. m The display problen persist (I tested ff and IE 11)

Am 09.03.2015 um 20:36 schrieb docwilmot:

**Comment by docwilmot** [comment]
Thanks. The height was in fact being lost. Changed the javascript execution and added an overflow class to the columns. Please test again.

**Comment by vtad** [comment]
I works correctly now!
