### ISSUE TITLE
Use HTML 5 color inputs for the color selections

### ISSUE THREAD

**Issue by hosef** [backdrop-contrib/fanciblock#11]
The color selection method currently uses normal text boxes. It would be a great UX improvement to be able to use a color picker, which could be done with an HTML 5 color input.

**Comment by stpaultim** [comment]
@hosef - I tested this one and it works as expected. I get the color picker as intended, however I notice the following:

1) There is no way for me to enter a hex value either directly into the fanciblock config page OR in the color picker. Is that expected? Is that ok?
2) Also, there is no way to view which color is currently selected, without opening the color picker.

**Comment by stpaultim** [comment]
![color-picker-2](https://user-images.githubusercontent.com/3144571/67332240-6a9e7080-f4e4-11e9-891d-519117ef7e15.jpg)

**Comment by stpaultim** [comment]
OK, now I notice that we can not enter a hex value into [Configurable Block Styles](https://github.com/backdrop-contrib/configurable_block_style) either. But, at least there we can see the currently selected color without having to open the color picker. 

I would consider this a UI improvement as it is. But, I think it would be nice to display the currently selected color. 

@hosef - Do you think we should just merge it as it is?

**Comment by hosef** [comment]
@stpaultim Which browser are you using to test the changes? On Firefox and Chrome for me, there is a place on the color picker where I can paste in a color code.

As for not being able to see the color you selected in the field, that is because of the styling from Seven. I created an issue to copy the input styling from the Color module to Seven, so that we will not have to keep copying them between modules in the future. backdrop/backdrop-issues#4155

**Comment by stpaultim** [comment]
OK, I see that you can enter a hex code in the color slider (ONLY) if you have it set for RGB. 

I've been testing in Chrome 77.0.3865.120 for the Mac. 

![Colors_and_Test___Local_Demo](https://user-images.githubusercontent.com/3144571/67349840-b534e280-f50e-11e9-8511-1dd3e953b7d1.png)

I just tested in Firefox 69.0.2 (64-bit) as well. This is what I'm seeing in Firefox (I can set hex code here as well, under rgb slider):

![Choose_a_color_and_Test___Local_Demo_and_Test___Local_Demo](https://user-images.githubusercontent.com/3144571/67349772-7bfc7280-f50e-11e9-8271-f68640da2567.png)

I think I just need to get used to using this specific tool.

**Comment by hosef** [comment]
Yeah, unfortunately, we don't have much control over the color picker that the browser or operating system provide.

**Comment by stpaultim** [comment]
@hosef - Can you resubmit the PR for this issue. I changed default branches and deleted the 1.1 branch that this PR was submitted to. Submit PR against 1.x-1.x.

**Comment by stpaultim** [comment]
@hosef - Any chance you still have this PR?

**Comment by hosef** [comment]
@stpaultim I updated the PR and put it on the 1.x-1.x branch. Do I need to make another PR for 1.x-2.x?

**Comment by hosef** [comment]
BTW, there is also an issue and PR to copy the styling of color inputs from the color module to Seven so that they would look consistent everywhere we are using them. https://github.com/backdrop/backdrop-issues/issues/4155

**Comment by stpaultim** [comment]
> I updated the PR and put it on the 1.x-1.x branch. Do I need to make another PR for 1.x-2.x?

Thanks for updating the PR. I'll try to take a look and see if we need something else for 1.x-2.x. I assume that I'll be able to translate your PR if necessary.
