### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/fanciblock#15]
I am just noticing that there is a 1.1 and a 1.x-1.x branch. More confusing is that the 1.1 is the default branch. 

Is there a reason for this this or is it just an oversight?

It appears that the 1.1 branch has about 1/2 dozen newer commits and that all the current pull requests are against that branch.

**Comment by stpaultim** [comment]
@docwilmot - told us to go ahead and fix the branches, but it appears that only the owner of the repo can change the default branch. 

I was trying to change the default branch to 1.x-1.x

**Comment by docwilmot** [comment]
Strangely I dont have access to change the branch either. @jenlampton did we do something with branch permissions recently? Can you give me ownership again?

**Comment by jenlampton** [comment]
@docwilmot likely, we've been shuffling contrib permissions. You now have admin. @stpaultim I made you maintainer too, so you should have more access. 

FYI It looks like anyone who wants admin on their repos may need to have 2FA enabled for GitHub in the future, as we're trying to reduce risk to contrib :) Follow https://github.com/backdrop-ops/contrib/issues/150 for updates.

**Comment by stpaultim** [comment]
@docwilmot - Say the word and I'll try to fix this for feel free to it yourself. But, I would love to get this sorted, because it's confusing for me to have these two branches.

:-)

**Comment by docwilmot** [comment]
The word

**Comment by stpaultim** [comment]
OK, I'll be working on this now. I assume that we're merging all changes into the 1.x-1.x branch and deleting the 1.1 branch.

**Comment by stpaultim** [comment]
@jenlampton - I still don't have permission to change the default branch. 

On Tatsu, I can change the default branch, but not here for fanciblock. 

![Branches_·_backdrop-contrib_tatsu](https://user-images.githubusercontent.com/3144571/69488014-d9dfeb00-0e29-11ea-8206-92bd23854f6f.png)

**Comment by jenlampton** [comment]
> I still don't have permission to change the default branch.

That's correct, this permission is missing for 'Maintainers' because GitHub is dumb! I have made you an Admin, but please make sure you have 2FA on b/c that will soon become a requirement for all contrib peeps who want admin on their things :)

**Comment by jenlampton** [comment]
oops, sorry. re-opeening :)

**Comment by stpaultim** [comment]
I have 2FA enabled and was able to change default branch and consolidate the old default branch into 1.x-1.x. 

Closing this issue.
