### ISSUE TITLE
Add stpaultim as co-maintainer

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/fanciblock#18]
I am about to submit a PR that adds me as a co-maintainer, if you are open to that. 

You gave me permission to merge Pull Requests in the past, but I don't want to keep doing that without being listed as co-maintainer. It would make things clearer.

Motivated by request in issue queue for a new release.

**Comment by docwilmot** [comment]
See comment on PR, will do manually. Thanks for offering and welcome @stpaultim
