### ISSUE TITLE
Mistake in help text - should be underscore NOT hyphens

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/fanciblock#20]
If you try to create a Fanciblock without giving it a title, you get messages telling you to create a block ID with 

> "A unique name for this Fanciblock. It must only contain lowercase letters, numbers and hyphens."

![Home_page__home____Cominnesota](https://user-images.githubusercontent.com/3144571/69197909-8e130600-0af8-11ea-94cb-49ad5cb24c66.png)

If I try adding a block ID with hypens, I get an error messages telling me.

> "The machine-readable name must contain only lowercase letters, numbers, and underscores."

![Home_page__home____Cominnesota](https://user-images.githubusercontent.com/3144571/69199548-e8fb2c00-0afd-11ea-82d1-f799d77aae5d.png)

- - - - - - - - 
PR by @stpaultim - https://github.com/backdrop-contrib/fanciblock/pull/21

**Comment by docwilmot** [comment]
This is fixed. Thanks @stpaultim
