### ISSUE TITLE
Admin title

### ISSUE THREAD

**Issue by keiserjb** [backdrop-contrib/fanciblock#29]
I discovered this module while looking for a Backdrop solution to certain elements of a Drupal site.  The D7 site uses the Bean module to create the blocks under Top Picks and Highlights.  https://www.jaxpubliclibrary.org/
We make use of them all over the site.  They also use the Field Collection module for content input.  Fanciblock ends up rendering in much the same way.  If I end up using it I'll have a lot of them and the ability to edit the Admin title would be very helpful in keeping them separate in the Layouts.  Also I'd like to be able to put the image on the bottom and the text at the top but that's secondary to being able to differentiate between all of the Fanciblock Image blocks.

**Comment by stpaultim** [comment]
The ability to add custom admin titles for blocks has been added to core and also works on this module.
