### ISSUE TITLE
Clean up README.md file

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/fanciblock#3]
Thanks for this port @docwilmot :)

Do you think I could talk you into changing the first heading in the README.md file?

The first heading is usually the name of the module (Please refer to our [contributor guidelines](https://github.com/backdrop-ops/contrib) for an [example README.md](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md) file). Because of that, backdropcms.org is set up to remove that first heading. If that heading is not formatted correctly, it won't be removed.

Take a look at the modules list to see the problem:
https://backdropcms.org/modules?keys=fanciblock

**Comment by stpaultim** [comment]
I am pretty sure that this has been fixed. Closing issue.
