### ISSUE TITLE
Can't add a box to an empty block

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/fanciblock#7]
If you delete all the boxes from a block there is an option to add a box. However, the add a box link generates an error:

```Argument 1 passed to backdrop_sort() must be of the type array, string given, called in /app/src/modules/contrib/fanciblock/fanciblock.box.admin.inc on line 9```

![Triplo___Demo](https://user-images.githubusercontent.com/3144571/66448391-0628df00-ea17-11e9-90b4-f64ca83c06dd.png)

NOTE: There is no option to add a box to a block that already has at least one box. It would be nice to be able to add and delete boxes.

**Comment by docwilmot** [comment]
@stpaultim I think this is fixed, please test.

**Comment by stpaultim** [comment]
@docwilmot - I tested and it works for me!!!

**Comment by stpaultim** [comment]
Seems to be fixed!
